[package]
name = "ABC306"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "a"
path = "src/a.rs"

[[bin]]
name = "b"
path = "src/b.rs"

[dependencies]
proconio = "=0.4.3"

[dev-dependencies]
cli_test_dir = "0.1.7"

